### ISSUE TITLE
OctoPrint Repository

### ISSUE THREAD

**Issue by Cjkeenan** [scottmudge/OctoPrint-MeatPack#2]
I tried finding this on the public OctoPrint Repo (https://plugins.octoprint.org/) and did not have any luck. Are there plans to post it there or is manual install going to be the only method for using this plugin?

**Comment by scottmudge** [comment]
I am working on posting it, I just wanted to test everything a bit more. 

But it looks like it's working well, so I'll go ahead and move forward with the submission process.

**Comment by scottmudge** [comment]
Alright I created a PR to add the plugin to the official repository:

https://github.com/OctoPrint/plugins.octoprint.org/pull/728
