### ISSUE TITLE
Marlin 2.0.8 (dev) Support

### ISSUE THREAD

**Issue by thinkyhead** [scottmudge/OctoPrint-MeatPack#5]
Hi! I'm just dropping off a note to let you know that this encoding is now supported by Marlin Firmware thanks to MarlinFirmware/Marlin#20802 by @ellensp. I will definitely be installing this plugin on all my OctoPrints!

**Comment by scottmudge** [comment]
Fantastic, thanks for letting me know, and thanks @ellensp for porting the code to Marlin! It's good to see they didn't need to modify their command parsing methods to accommodate the whitespace removal mode. Hopefully Prusa fixes it on their end.
